language: node_js
node_js:
- '12'
cache:
  yarn: true
script:
- yarn build
deploy:
  edge: true
  provider: pages:git
  cleanup: false
  local_dir: "./recipes/.vuepress/dist"
  token:
    secure: PJYkdrHLKTRUHcPOohwcXKCYPEAeNk0a0FutL6uWDSw5BiREa/Bb1guZRUwZRyQrTZBwnfYYUjTidQpXHTs6q76Mrp6hGFUOhP6KmowAPJK+AKW1W6nqPnjv4Fdklgh+Dm0ArV1qlcyx1rMDLDbPKpat2PH8H2uEgs8yUlaHS2SE7BbHQ8Chd7I25DEWFXF6h+cCZShnpQPfKgCQdNM9zgV0RZODaefWzQA8ubvRLMAy33ufJS/tBAWX0EFbyCQpYT9LGCxbFqGHGqkA8jCg2RD1a8IkR3qaqSyvn6rJ8mqGztxOIYpuXfS6xgk2aEj6kv4ol3btMRrN9eQsn1Wuwp7kBKvueAKMMViWfJj7Bi642kZ67/y2SWTMU6hx5g+HpF2tO2qkiRlPQsx3rH2ZpSg0h3jDpNIIbANhxAEMSpqzrdFQCzzfgGh5ZYyxIrpfMjRtHaGeEX/IEOwXPNuluJK1Szny4A95mfUQtA88CwjWr4UCfq8Ef8B0WeyM9advWw6N1qIvQ9YfKpcmjU49yTUs736RjyrY7LZAocUW1wFh3ZOJm8v1O2Bf+kbOr0DE3/B9H+0hyOoHpD1ilh3E+nwF9zMZv1BtUH9vosN/oXqMdz+sfs7o2Qix+5RYTzkDG3YFsPNyXdx4ZsYICvIYVOBt9v7Mm6l87OCLt8+T4ho=
  keep_history: true
  repo: octo-woapi/cookbook
  on:
    branch: master
